install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true

# Uncomment the next line to define a global platform for your project
platform :ios, 10.0
inhibit_all_warnings!

target 'XTIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XTInputKitDemo
  pod 'XTIBaseTool', :path => '../XTIBaseTool'
  pod 'XTILoger', :path => '../XTILoger'
  pod 'XTINetwork', :path => '../XTINetwork'
  pod 'SnapKit'
end
